/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.example;

import java.time.LocalDate;

import org.example.cache.PaymentCache;
import org.example.dto.UserDTO;
import org.example.model.Payment;
import org.example.model.User;

/**
 *
 * @author maxi
 */
public class BalancesJPanel extends javax.swing.JPanel {
    UserDTO user;
    LocalDate date;

    /**
     * Creates new form BalancesJPanel
     */
    public BalancesJPanel(UserDTO user) {
        initComponents();
        this.user = user;
        this.date = LocalDate.now();
        PaymentCache paymentCache = PaymentCache.getInstance(user);
        jTextAreaUsersBalance.setText("Pagos de " + user.getEmail() + ":\n\n");
        for (Payment payment : paymentCache.getPayments()) {
            if (payment.getPayer().getId() == user.getId()) {
                jTextAreaUsersBalance.append("Pagó: " + payment.getAmount() + " a " + payment.getRecipient().getEmail() + " el " + payment.getDate() + "\n");
            } else if (payment.getRecipient().getId() == user.getId()) {
                jTextAreaUsersBalance.append("Recibió: " + payment.getAmount() + " de " + payment.getPayer().getEmail() + " el " + payment.getDate() + "\n");
            }
        }

        jLabelBalanceToDate.setText("Balance al " + date.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelBalanceToDate = new javax.swing.JLabel();
        jButtonDate = new javax.swing.JButton();
        jTextAreaUsersBalance = new javax.swing.JTextArea();

        jLabelBalanceToDate.setText("jLabelBalanceToDate");

        jButtonDate.setText("jButtonDate");
        jButtonDate.setMaximumSize(new java.awt.Dimension(72, 30));
        jButtonDate.setMinimumSize(new java.awt.Dimension(72, 30));

        jTextAreaUsersBalance.setColumns(20);
        jTextAreaUsersBalance.setRows(5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelBalanceToDate)
                .addGap(144, 144, 144)
                .addComponent(jButtonDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextAreaUsersBalance, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBalanceToDate)
                    .addComponent(jButtonDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jTextAreaUsersBalance, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addGap(105, 105, 105))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDate;
    private javax.swing.JLabel jLabelBalanceToDate;
    private javax.swing.JTextArea jTextAreaUsersBalance;
    // End of variables declaration//GEN-END:variables
}
