/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

import org.example.cache.PaymentCache;
import org.example.dto.PaymentDTO;
import org.example.dto.UserDTO;
import org.example.model.Payment;
import org.example.model.Response;
import org.example.model.User;
import org.example.service.PaymentService;
import org.example.service.UserService;

import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author maxi
 */
public class EditPaymentJFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditPaymentJFrame.class.getName());

    private UserDTO user;
    private Payment payment;
    /**
     * Creates new form NewPaymentJFrame
     */
    public EditPaymentJFrame(UserDTO user, Payment payment) {
        initComponents();
        this.user = user;
        this.payment = payment;
        jLabelPaymentEdit.setText("Editar Pago: ID " + payment.getId() + " - " + payment.getPayer().getName() + " -> " + payment.getRecipient().getName() + payment.getAmount() + " (" + payment.getDate() + ")");

        UserService userService = new UserService();
        Response response = userService.getAllUsersButOne(user.getId());
        if (response.isSuccess()) {
            String responseString = "Usuarios Registrados:";
            List<User> list = response.getData();
            for (User u : list) {
                responseString = responseString + "\nID: " + u.getId() +" -> "+ u.getName()+" -> "+u.getEmail();
            }
            jTextAreaUsuarios.setText(responseString);
            jTextAreaUsuarios.setEditable(false); // Solo lectura
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAmount = new javax.swing.JLabel();
        jButtonEdit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaUsuarios = new javax.swing.JTextArea();
        jLabelPaymentEdit = new javax.swing.JLabel();
        jLabelDate = new javax.swing.JLabel();
        jLabelRecipientId = new javax.swing.JLabel();
        jFormattedTextFieldDate = new javax.swing.JFormattedTextField();
        jFormattedTextFieldAmount = new javax.swing.JFormattedTextField();
        jFormattedTextFieldRecipientId = new javax.swing.JFormattedTextField();
        jButtonDelete = new javax.swing.JButton();
        jLabelPayerId = new javax.swing.JLabel();
        jFormattedTextFieldPayerId = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelAmount.setText("Monto");

        jButtonEdit.setText("Editar");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jScrollPane1.setSize(new java.awt.Dimension(380, 0));

        jTextAreaUsuarios.setColumns(20);
        jTextAreaUsuarios.setRows(5);
        jScrollPane2.setViewportView(jTextAreaUsuarios);

        jScrollPane1.setViewportView(jScrollPane2);

        jLabelPaymentEdit.setText("Editar Pago");

        jLabelDate.setText("Día");

        jLabelRecipientId.setText("Destinatario");

        jFormattedTextFieldDate.setColumns(6);
        jFormattedTextFieldDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("d/M/yy"))));

        jFormattedTextFieldAmount.setColumns(6);
        jFormattedTextFieldAmount.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        jFormattedTextFieldRecipientId.setColumns(6);
        jFormattedTextFieldRecipientId.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jButtonDelete.setBackground(new java.awt.Color(255, 51, 51));
        jButtonDelete.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jButtonDelete.setText("Eliminar");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jLabelPayerId.setText("Pagador");

        jFormattedTextFieldPayerId.setColumns(6);
        jFormattedTextFieldPayerId.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPaymentEdit)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonEdit)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabelAmount)
                                            .addComponent(jLabelDate))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jFormattedTextFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jFormattedTextFieldAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(48, 48, 48)
                                .addComponent(jButtonDelete))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelRecipientId)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jFormattedTextFieldRecipientId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelPayerId)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jFormattedTextFieldPayerId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 55, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelPaymentEdit)
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelPayerId)
                        .addComponent(jFormattedTextFieldPayerId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelRecipientId)
                        .addComponent(jFormattedTextFieldRecipientId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDate)
                    .addComponent(jFormattedTextFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAmount)
                    .addComponent(jFormattedTextFieldAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEdit)
                    .addComponent(jButtonDelete))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        //TODO el usuario tiene que ser el pagador o receptor. No puede hacer un pago que no lo involucre.
        PaymentDTO dto = new PaymentDTO();
        PaymentCache paymentCache = PaymentCache.getInstance(user);

        dto.setId(payment.getId());
        try {
            String dateInput = jFormattedTextFieldDate.getText().trim();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("d/M/yy");
            LocalDate date = LocalDate.parse(dateInput, formatter);
            System.out.println("Fecha válida: " + date);
            dto.setDate(date);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error de fecha", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
            Object value = jFormattedTextFieldRecipientId.getValue();
            if (value == null) throw new NullPointerException();
            int recipientIdInput = ((Number) value).intValue();
            dto.setRecipientId(recipientIdInput);
        }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Ingrese un ID válido para el destinatario.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
        }
        try{
            Object value = jFormattedTextFieldPayerId.getValue();
            if (value == null) throw new NullPointerException();
            int payerIdInput = ((Number) value).intValue();
            dto.setPayerId(payerIdInput);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Ingrese un ID válido para el pagador.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
        Object amountValue = jFormattedTextFieldAmount.getValue();
        if (amountValue == null) throw new NullPointerException();

        double amount = ((Number) amountValue).doubleValue();
        dto.setAmount(amount);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ingrese un monto válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        PaymentService paymentService = new PaymentService();
        Response response = paymentService.editPayment(dto);
        if (response.isSuccess()){
            JOptionPane.showMessageDialog(this, "Pago editado correctamente.");
            // Actualizar el pago en el cache del usuario
            Payment paymentToUpload = (Payment) response.getObj();
            Response cacheResponse = paymentCache.editPayment(paymentToUpload);
            if(cacheResponse.isSuccess()) {
                JOptionPane.showMessageDialog(this, "Pago cargado en el cache del usuario correctamente.");
                IndexJFrame in = new IndexJFrame(user);
                in.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Error al cargar el pago en el cache: " + cacheResponse.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar el pago: " + response.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        this.dispose();

    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JFormattedTextField jFormattedTextFieldAmount;
    private javax.swing.JFormattedTextField jFormattedTextFieldDate;
    private javax.swing.JFormattedTextField jFormattedTextFieldPayerId;
    private javax.swing.JFormattedTextField jFormattedTextFieldRecipientId;
    private javax.swing.JLabel jLabelAmount;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelPayerId;
    private javax.swing.JLabel jLabelPaymentEdit;
    private javax.swing.JLabel jLabelRecipientId;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaUsuarios;
    // End of variables declaration//GEN-END:variables
}
