/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.example;

import org.example.cache.UserCache;
import org.example.dto.UserDTO;
import org.example.model.Response;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author maxi
 */
public class UserJPanel extends javax.swing.JPanel {
    private UserDTO user;
    private UserBalanceJPanel userBalanceJPanel;
    private AllUsersJPanel allUsersJPanel;

    /**
     * Creates new form UserJPanel
     */
    public UserJPanel(UserDTO user) {
        initComponents();
        this.user = user;

        UserBalanceJPanel userBalanceJPanel = new UserBalanceJPanel(user,user);
        AllUsersJPanel allUsersJPanel = new AllUsersJPanel(user);
        jPanel1.setLayout(new CardLayout());
        jPanel1.add(userBalanceJPanel, "Balance");
        jPanel1.add(allUsersJPanel, "AllUsers");
        CardLayout cardLayout = (CardLayout) jPanel1.getLayout();
        cardLayout.show(jPanel1, "AllUsers"); // Muestra el panel de todos por defecto
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelViewUser = new javax.swing.JLabel();
        jTextFieldUserId = new javax.swing.JTextField();
        jButtonFilterUser = new javax.swing.JButton();
        jButtonViewAll = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));

        jPanel1.setMinimumSize(new java.awt.Dimension(500, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jLabelViewUser.setText("Cer usuario con ID:");

        jTextFieldUserId.setColumns(3);

        jButtonFilterUser.setText("Filtrar por ID");
        jButtonFilterUser.setToolTipText("");
        jButtonFilterUser.setMaximumSize(new java.awt.Dimension(100, 23));
        jButtonFilterUser.setMinimumSize(new java.awt.Dimension(100, 23));
        jButtonFilterUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFilterUserActionPerformed(evt);
            }
        });

        jButtonViewAll.setText("Ver todos");
        jButtonViewAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelViewUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonFilterUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143)
                .addComponent(jButtonViewAll)
                .addGap(0, 400, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelViewUser)
                    .addComponent(jTextFieldUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFilterUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonViewAll))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFilterUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFilterUserActionPerformed

        try{
            int id = Integer.parseInt(jTextFieldUserId.getText().trim());//Obtengo el id del usuario amigo
            Response<UserDTO> responseFriend = UserCache.getInstance().getById(id);//Busco el usuario en el cache
            if (responseFriend.isSuccess()) {
                UserDTO friend = responseFriend.getObj();//Obtengo el usuario amigo
                //Si el usuario existe, lo muestro en el panel de balance
                CardLayout cardLayout = (CardLayout) jPanel1.getLayout();
                userBalanceJPanel = new UserBalanceJPanel(user, friend); // nuevo panel
                jPanel1.add(userBalanceJPanel, "BalanceTemp_" + friend.getId()); // agregás con clave única por si cambian
                cardLayout.show(jPanel1, "BalanceTemp_" + friend.getId()); // mostrás ese

            } else {
                //Si no existe, muestro un mensaje de error
                System.out.println("El usuario no existe.");
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, "Error al filtrar por ID:\n", "Error", JOptionPane.ERROR_MESSAGE);
        }


        //ACA DEBO AGREGAR QUE VA A HACER EL BOTON DE FILTRAR
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFilterUserActionPerformed

    private void jButtonViewAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewAllActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) jPanel1.getLayout();
        cardLayout.show(jPanel1, "AllUsers"); // Cambia al panel de todos los usuarios
        
    }//GEN-LAST:event_jButtonViewAllActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFilterUser;
    private javax.swing.JButton jButtonViewAll;
    private javax.swing.JLabel jLabelViewUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldUserId;
    // End of variables declaration//GEN-END:variables
}
